networks:
  traefik_default:
    external: true

services:
  server:
    cap_add:
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    image: git.zarantonello.dev/university/notes:v2.9.1@sha256:61a2d385e86c9971a37fc487ec6fe62097bce94e7e387335b807ded6b77cafb0
    labels:
      traefik.enable: true
      traefik.http.routers.university-notes.entrypoints: cloudflared
      traefik.http.routers.university-notes.rule: Host(`ice-notes.zarantonello.dev`)
      traefik.http.services.university-notes.loadbalancer.server.port: 80
    networks:
      - traefik_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 45383:45383
