networks:
  traefik_default:
    external: true

services:
  server:
    cap_add:
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    image: git.zarantonello.dev/university/notes:v2.4.4@sha256:65cdeb35807ff09d7e4b2835e1155c8f8ae6ce2c661eeb9af196dd33b540545c
    labels:
      traefik.enable: true
      traefik.http.routers.university-notes.entrypoints: cloudflared
      traefik.http.routers.university-notes.rule: Host(`ice-notes.zarantonello.dev`)
      traefik.http.services.university-notes.loadbalancer.server.port: 80
    networks:
      - traefik_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 45383:45383
