networks:
  traefik_default:
    external: true

services:
  server:
    cap_add:
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    image: git.zarantonello.dev/university/notes:v1.38.14@sha256:85b60a80e72cf3a7e767a7c51e7b6cdd92a12541c7e35a9e26bc53c242bcd7ed
    labels:
      traefik.enable: true
      traefik.http.routers.university-notes.entrypoints: cloudflared
      traefik.http.routers.university-notes.rule: Host(`ice-notes.zarantonello.dev`)
      traefik.http.services.university-notes.loadbalancer.server.port: 80
    networks:
      - traefik_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 45383:45383
