concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.job }}

jobs:
  build:
    container:
      image: git.zarantonello.dev/infra/ci:v1.1.11@sha256:cd93ca425527d9d0e93f4f94b4ba4b942dd42a9ae806bbf915e78d70dea3191c
    runs-on: srv-large
    steps:
      - uses: https://data.forgejo.org/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - run: buildah login git.zarantonello.dev -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWORD }}
      - run: buildah build --tag git.zarantonello.dev/${{ forge.repository }}:${{ forge.ref_name }} .
      - run: buildah push git.zarantonello.dev/${{ forge.repository }}:${{ forge.ref_name }}

"on":
  push:
    tags:
      - "*"
