concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  build:
    container:
      image: git.zarantonello.dev/infra/ci:v2.3.66@sha256:5bceab7337a649f4fec4b4546e850b10faff8359b59413640f9eaad9cd7d9671
    name: Build the container
    runs-on: srv-large
    steps:
      - name: Clone the repository
        uses: https://data.forgejo.org/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Login to the container registry
        run: docker login git.zarantonello.dev -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build the container image
        run: docker build --tag git.zarantonello.dev/${{ forge.repository }}:${{ forge.ref_name }} .
      - name: Push the container image
        run: docker push git.zarantonello.dev/${{ forge.repository }}:${{ forge.ref_name }}

name: build.yaml

"on":
  push:
    tags:
      - "*"
