concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check-commitizen:
    container:
      image: git.zarantonello.dev/infra/ci:v2.3.36@sha256:828413ae6d52b059b10a899feacd8476f20f058d15bcf40b2718d18ab9bfe501
    name: Check the PR title
    runs-on: srv-generic
    steps:
      - name: Run commitizen
        run: cz check --message '${{ forge.event.pull_request.title }}'

name: check-commitizen.yaml

"on":
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
