concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.job }}

jobs:
  check:
    container:
      image: git.zarantonello.dev/infra/ci:v1.1.21@sha256:d9164925e34d0d9b3034002400a36813c422881a800a80593cd1cdb1d88495f0
    name: Checks
    runs-on: srv-large
    steps:
      - name: Clone the repository
        uses: https://data.forgejo.org/actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Restore the bun cache
        uses: https://data.forgejo.org/actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          path: /root/.bun/install/cache
      - name: Install dependencies with bun
        run: bun install
      - name: Run prettier
        run: bun run prettier --check .
      - name: Run biome
        run: bun run biome ci
      - name: Run astro check
        run: bun run check
      - name: Build the website
        run: bun run build
      - name: Check for latex rendering errors
        run: sh -c '! grep cc0000 dist/ -rl'

name: check.yaml

"on":
  pull_request:
    branches:
      - main
