concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check-commitizen:
    container:
      image: git.zarantonello.dev/infra/ci:v2.3.50@sha256:ea08a342b501b81256e0c37b6ba5c1e9485ca9a1ccb7a91936cd8f6a79c67174
    name: Check the PR title
    runs-on: srv-generic
    steps:
      - name: Run commitizen
        run: cz check --message '${{ forge.event.pull_request.title }}'

name: check-commitizen.yaml

"on":
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
