concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.job }}

jobs:
  check-commitizen:
    container:
      image: git.zarantonello.dev/infra/ci:v2.2.7@sha256:38f123c11ed0b69f904788fadd8324c92122a88fb347e54c568ab6f8e61c80d6
    name: Check the PR title
    runs-on: srv-generic
    steps:
      - name: Run commitizen
        run: cz check --message '${{ forge.event.pull_request.title }}'

name: check-commitizen.yaml

"on":
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
