concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check-yamllint:
    container:
      image: git.zarantonello.dev/infra/ci:v2.3.39@sha256:b65c12e4baaeaf7a6818e1a0ab67b8cf03ef2860034747c60059523e0f0ca117
    name: Lint yaml files
    runs-on: srv-generic
    steps:
      - name: Clone the repository
        uses: https://data.forgejo.org/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run yamllint
        run: yamllint .

name: check-yamllint.yaml

"on":
  pull_request:
    branches:
      - main
