concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.job }}

jobs:
  check:
    container:
      image: git.zarantonello.dev/infra/ci:v1.1.11@sha256:cd93ca425527d9d0e93f4f94b4ba4b942dd42a9ae806bbf915e78d70dea3191c
    runs-on: srv-large
    steps:
      - uses: https://data.forgejo.org/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: https://data.forgejo.org/actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          path: /root/.bun/install/cache
      - run: bun install
      - run: bun run prettier --check .
      - run: bun run biome ci
      - run: bun run check

"on":
  pull_request:
    branches:
      - main
