concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.job }}

jobs:
  check:
    container:
      image: git.zarantonello.dev/infra/ci:v1.1.1@sha256:d8b909dc9603e6e965156c06f9cc6e674b73c7a5cbc14897551254fc30f8af2c
    runs-on: srv-large
    steps:
      - uses: https://data.forgejo.org/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: https://data.forgejo.org/actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          path: /root/.bun/install/cache
      - run: bun install
      - run: bun run prettier --check .
      - run: bun run biome ci
      - run: bun run check

"on":
  pull_request:
    branches:
      - main
