concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.job }}

jobs:
  check:
    container:
      image: git.zarantonello.dev/infra/ci:v1.1.28@sha256:686364bb3537347897d5f3aa7a505de68013d95668ad53b25b6a1b96750f79bb
    name: Checks
    runs-on: srv-large
    steps:
      - name: Clone the repository
        uses: https://data.forgejo.org/actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Restore the bun cache
        uses: https://data.forgejo.org/actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          path: /root/.bun/install/cache
      - name: Install dependencies with bun
        run: bun install
      - name: Run prettier
        run: bun run prettier --check .
      - name: Run biome
        run: bun run biome ci
      - name: Run astro check
        run: bun run check
      - name: Build the website
        run: bun run build
      - name: Check for latex rendering errors
        run: sh -c '! grep cc0000 dist/ -rl'

name: check.yaml

"on":
  pull_request:
    branches:
      - main
