concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.job }}

jobs:
  check-hadolint:
    container:
      image: git.zarantonello.dev/infra/ci:v1.1.25@sha256:a9c92719ff92c602271cf7681086ddc155f31d9f5639b9746f793775fef0273e
    name: Lint Dockerfiles
    runs-on: srv-generic
    steps:
      - name: Clone the repository
        uses: https://data.forgejo.org/actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Run hadolint
        run: for i in $(find . -name Dockerfile) ; do hadolint $i ; done

name: check-hadolint.yaml

"on":
  pull_request:
    branches:
      - main
