concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check-commitizen:
    container:
      image: git.zarantonello.dev/infra/ci:v2.4.4@sha256:41b117803e7189bf56440d389b8506a073f78628e1f144fe0281b6301ebd0182
    name: Check the PR title
    runs-on: srv-generic
    steps:
      - name: Run commitizen
        run: cz check --message '${{ forge.event.pull_request.title }}'

name: check-commitizen.yaml

"on":
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
