concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check-yamllint:
    container:
      image: git.zarantonello.dev/infra/ci:v2.3.71@sha256:f3ed47d066e63bbfa9044f060b56bd4ef3fb4594cf10dba0d788867b0073e862
    name: Lint yaml files
    runs-on: srv-generic
    steps:
      - name: Clone the repository
        uses: https://data.forgejo.org/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run yamllint
        run: yamllint .

name: check-yamllint.yaml

"on":
  pull_request:
    branches:
      - main
