concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.job }}

jobs:
  check:
    container:
      image: git.zarantonello.dev/infra/ci:latest@sha256:f0060036e948e91050ef5ad4ce5654c7433b46a7d9161fa511678b10c5c550a2
    runs-on: srv-large
    steps:
      - uses: https://data.forgejo.org/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: https://data.forgejo.org/actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          path: /root/.bun/install/cache
      - run: bun install
      - run: bun run prettier --check .
      - run: bun run biome ci
      - run: bun run check

"on":
  pull_request:
    branches:
      - main
