services:
  workspace:
    image: git.zarantonello.dev/infra/ci:v2.3.38@sha256:b16b5087e9c3bf1552cbbb028ee6aac4cb330c411d81f8638ace1c9f85a603b2
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:cached
