apiVersion: apps/v1
kind: Deployment
metadata:
  name: ice-notes
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: ice-notes
      apps.zarantonello.dev/namespace: ice-notes
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: ice-notes
        apps.zarantonello.dev/namespace: ice-notes
    spec:
      containers:
        - image: git.zarantonello.dev/davide/ice-notes:latest@sha256:0cf32cc4cf3bd12be2bfab1bdfa49c8b7430132dc5e5e974f626754d85372916
          imagePullPolicy: IfNotPresent
          name: ice-notes
          ports:
            - containerPort: 80
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - ALL
            readOnlyRootFilesystem: true
      enableServiceLinks: false
      nodeSelector:
        kubernetes.io/hostname: srv-0-nbg-hetz
      securityContext:
        fsGroup: 45383
        runAsGroup: 45383
        runAsNonRoot: true
        runAsUser: 45383
        seccompProfile:
          type: RuntimeDefault
